name: Keep Alive

on:
    schedule:
        # Runs every 9 minutes
        - cron: "*/9 * * * *"
    workflow_dispatch:

jobs:
    ping:
        runs-on: ubuntu-latest
        steps:
            - name: Ping the API
              run: |
                  echo "Pinging server..."
                  curl -f https://brainwaves-quizce.onrender.com/api/v1/health || exit 1
